# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: citest
  TAG: v2
  PROJECT_ID: subtle-amulet-340607
  GAR_NAME: doc-regi

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build and Push to GCP
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Output ArtifcatRegistry URL
        id: vars
        run: echo ::set-output name=gar_url::asia-northeast3-docker.pkg.dev/$PROJECT_ID/$GAR_NAME/citest:$TAG

      - name: Test URL
        run: echo ${{ steps.vars.outputs.gar_url }}

      - name: Build Docker Image
        run: docker build -t ${{ steps.vars.outputs.gar_url }} .

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker asia-northeast3-docker.pkg.dev --quiet

      - name: Docker Images Check
        run: docker images

      - name: Push Docker Image to GAR
        run: docker push ${{ steps.vars.outputs.gar_url }}
