# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: citest
  GIT_TAG: v2

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: subtle-amulet-340607
      GAR_NAME: doc-regi

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Build Docker Image
        run: docker build -t citest:$GIT_TAG .

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker asia-northeast3-docker.pkg.dev --quiet

      - name: Docker Images Check
        run: docker images

      - name: Push Docker Image to GAR
        run: docker push asia-northeast3-docker.pkg.dev/$PROJECT_ID/$GAR_NAME/citest:$GIT_TAG
