# This is a basic workflow to help you get started with Actions
# asia-northeast3-docker.pkg.dev/subtle-amulet-340607/doc-regi/citest:v2

name: CI/CD

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: citest
  TAG: v4
  PROJECT_ID: subtle-amulet-340607
  GAR_NAME: doc-regi

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build and Push to GCP
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      #gcloud 설정
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      # 저장소 명 저장
      - name: Output ArtifcatRegistry URL
        id: vars
        run: echo ::set-output name=gar_url::asia-northeast3-docker.pkg.dev/$PROJECT_ID/$GAR_NAME/summerimg:$TAG

      #저장명 확인
      - name: Test URL
        run: echo ${{ steps.vars.outputs.gar_url }}

      #이미지 말기
      - name: Build Docker Image
        run: docker build -t ${{ steps.vars.outputs.gar_url }} .

      # gar 사용자 인증설정
      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker asia-northeast3-docker.pkg.dev --quiet

      #도커 이미지들 체크
      - name: Docker Images Check
        run: docker images

      #gar에 도커이미지 올리기
      - name: Push Docker Image to GAR
        run: docker push ${{ steps.vars.outputs.gar_url }}

      #Cloud Run에 배포
      - name: Deploy to Cloud Run.
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: real-final
          region: asia-northeast3
          image: ${{ steps.vars.outputs.gar_url }}
